name: 'install-test'

on:
  schedule:
    - cron: "30 22 * * *"
  push:
    branches:
      - main

jobs:
  install-test:
    runs-on: macos-26
    steps:
    - uses: actions/checkout@v5
    - name: Install php services
      run: |
        brew update || true
        brew upgrade $(brew outdated --formula -q) || true     
        brew  tap valet-sh/php
        brew  install vsh-php56
        brew  install vsh-php70
        brew  install vsh-php71
        brew  install vsh-php72
        brew  install vsh-php73
        brew  install vsh-php74
        brew  install vsh-php80
        brew  install vsh-php81
        brew  install vsh-php82
        brew  install vsh-php83
        brew  install vsh-php84
        brew  install vsh-php85